//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.03 at 10:18:23 AM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://requests.soapservice.jerimkaura.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jerimkaura.soapservice.requests;
